### ISSUE TITLE
NullPointerException in SettingsFragment

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/android-wail-app#133]
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.artemzin.android.wail/com.artemzin.android.wail.ui.activity.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2229)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2279)
at android.app.ActivityThread.access$600(ActivityThread.java:142)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5105)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.artemzin.android.wail.ui.fragment.main.SettingsFragment.onCreate(SettingsFragment.java:176)
at android.app.Fragment.performCreate(Fragment.java:1676)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:855)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1058)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1040)
at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1836)
at android.app.Activity.onCreate(Activity.java:904)
at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:255)
at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:122)
at com.artemzin.android.wail.ui.activity.BaseActivity.onCreate(BaseActivity.java:21)
at com.artemzin.android.wail.ui.activity.MainActivity.onCreate(MainActivity.java:93)
at android.app.Activity.performCreate(Activity.java:5220)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1086)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2193)
... 11 more`

**Comment by ilya-murzinov** [comment]
This issue is useless :(
