### ISSUE TITLE
NullPointerException in TracksListFragment

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/android-wail-app#134]
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.artemzin.android.wail/com.artemzin.android.wail.ui.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setTitle(java.lang.CharSequence)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5696)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setTitle(java.lang.CharSequence)' on a null object reference
at com.artemzin.android.wail.ui.fragment.main.TracksListFragment.onCreate(TracksListFragment.java:80)
at android.app.Fragment.performCreate(Fragment.java:2127)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:876)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1097)
at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2022)
at android.app.Activity.onCreate(Activity.java:943)
at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:255)
at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:122)
at com.artemzin.android.wail.ui.activity.BaseActivity.onCreate(BaseActivity.java:21)
at com.artemzin.android.wail.ui.activity.MainActivity.onCreate(MainActivity.java:93)
at android.app.Activity.performCreate(Activity.java:5958)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
... 10 more`

**Comment by ilya-murzinov** [comment]
This issue is useless :(
