### ISSUE TITLE
IllegalArgumentException: AppCompat does not support the current theme features

### ISSUE THREAD

**Issue by evoyager** [artem-zinnatullin/android-wail-app#141]
When I try to build application, crash report "IllegalArgumentException: AppCompat..." occurred.

I find solution from this tutorial:
https://github.com/TonicArtos/SuperSLiM/issues/76

To fix it, I changed values -> themes.xml from
< item name="android:windowNoTitle">true< /item>
to
< item name="windowNoTitle">true< /item>
and it works!

Android Studio 1.1.0
Branch: develop.
Commit: 39c8a7f18a
VersionName '0.7.2 beta'.
API: 21.

Here all crash report:

06-05 17:49:56.304    1361-1361/com.artemzin.android.wail E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.artemzin.android.wail, PID: 1361
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.artemzin.android.wail/com.artemzin.android.wail.ui.activity.MainActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
            at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:360)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at com.artemzin.android.wail.ui.activity.MainActivity.onCreate(MainActivity.java:94)
            at android.app.Activity.performCreate(Activity.java:5937)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)

**Comment by joonki34** [comment]
I have tried his solution and it works on my machine too. I am using Android Studio 1.2.1.1.

**Comment by ilya-murzinov** [comment]
Can some of you please submit a PR with the fix?
